# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditarContenido.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from windows import Conexion


class Ui_WindowEditarContenido(object):
    def setupUi(self, WindowEditarContenido):
        WindowEditarContenido.setObjectName("WindowEditarContenido")
        WindowEditarContenido.resize(514, 481)
        WindowEditarContenido.setMinimumSize(QtCore.QSize(514, 481))
        WindowEditarContenido.setMaximumSize(QtCore.QSize(514, 481))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/298809902_539628011298194_5839572564237821349_n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WindowEditarContenido.setWindowIcon(icon)
        WindowEditarContenido.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label = QtWidgets.QLabel(WindowEditarContenido)
        self.label.setGeometry(QtCore.QRect(20, 90, 201, 21))
        self.label.setStyleSheet("font: 75 11.5pt \"SansSerif\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(WindowEditarContenido)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(20, 120, 471, 41))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    font: 9pt \"MS Sans Serif\";\n"
"    border: 2px solid rgb(158, 158, 158);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(WindowEditarContenido)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 270, 471, 71))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    font: 9pt \"MS Sans Serif\";\n"
"    border: 2px solid rgb(158, 158, 158);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(WindowEditarContenido)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 211, 21))
        self.label_2.setStyleSheet("font: 75 11.5pt \"SansSerif\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(WindowEditarContenido)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 141, 16))
        self.label_3.setStyleSheet("font: 75 11.5pt \"SansSerif\";")
        self.label_3.setObjectName("label_3")
        self.btn_Nuevo = QtWidgets.QPushButton(WindowEditarContenido)
        self.btn_Nuevo.setGeometry(QtCore.QRect(270, 420, 115, 30))
        self.btn_Nuevo.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo.setFlat(False)
        self.btn_Nuevo.setObjectName("btn_Nuevo")
        self.btn_Eliminar = QtWidgets.QPushButton(WindowEditarContenido)
        self.btn_Eliminar.setGeometry(QtCore.QRect(390, 420, 115, 30))
        self.btn_Eliminar.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Eliminar.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(170, 0, 0);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Eliminar.setFlat(False)
        self.btn_Eliminar.setObjectName("btn_Eliminar")
        self.lineEdit_2 = QtWidgets.QLineEdit(WindowEditarContenido)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 200, 471, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    font: 9pt \"MS Sans Serif\";\n"
"    border: 2px solid rgb(158, 158, 158);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(WindowEditarContenido)
        self.label_4.setGeometry(QtCore.QRect(20, 350, 141, 16))
        self.label_4.setStyleSheet("font: 75 11.5pt \"SansSerif\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(WindowEditarContenido)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 370, 471, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    font: 9pt \"MS Sans Serif\";\n"
"    border: 2px solid rgb(158, 158, 158);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(WindowEditarContenido)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 291, 21))
        self.label_5.setStyleSheet("font: 75 11.5pt \"SansSerif\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(WindowEditarContenido)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 40, 471, 41))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(217, 217, 217);\n"
"    font: 9pt \"MS Sans Serif\";\n"
"    border: 2px solid rgb(158, 158, 158);\n"
"    border-radius: 15px;\n"
"    \n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.btn_Nuevo_2 = QtWidgets.QPushButton(WindowEditarContenido)
        self.btn_Nuevo_2.setGeometry(QtCore.QRect(40, 420, 115, 30))
        self.btn_Nuevo_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo_2.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo_2.setFlat(False)
        self.btn_Nuevo_2.setObjectName("btn_Nuevo_2")

        self.retranslateUi(WindowEditarContenido)
        self.btn_Eliminar.clicked.connect(WindowEditarContenido.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WindowEditarContenido)

        self.btn_Nuevo_2.clicked.connect(self.buscar_por_titulo_actualizar)
        self.btn_Nuevo.clicked.connect(self.modificar_soluciones)

    def buscar_por_titulo_actualizar(self):
        id_pregunta = self.lineEdit_5.text()
        id_pregunta = str("'"+id_pregunta+"'")
        from windows import Conexion
        self.datos = Conexion.DataBase()
        self.pregunta = self.datos.buscar_solucion(id_pregunta)
        if len(self.pregunta) != 0:
            self.Id = self.pregunta[0][0]
            self.lineEdit.setText(self.pregunta[0][1])
            self.lineEdit_2.setText(self.pregunta[0][2])
            self.lineEdit_3.setText(self.pregunta[0][3])
            self.lineEdit_4.setText(self.pregunta[0][4])

        else:
            import tkinter
            from tkinter import messagebox
            error = tkinter.messagebox.showerror("No exite", "No existen estos datos")

    def modificar_soluciones(self):
        if self.pregunta != '':
            titulo = self.lineEdit.text()
            area = self.lineEdit_2.text()
            solucion = self.lineEdit_3.text()
            clave = self.lineEdit_4.text()
            self.datos = Conexion.DataBase()
            self.act = self.datos.actualizar_solucion(self.Id, titulo, area, solucion, clave)
            if self.act == 1:
                import tkinter
                from tkinter import messagebox
                hecho = tkinter.messagebox.showinfo("Actualzado", "Los datos fueron actualizados satisfactoriamente")
                print("xd")
            elif self.act == 0:
                print("error")
            else:
                import tkinter
                from tkinter import messagebox
                hecho = tkinter.messagebox.showinfo("Posiblemente hay un error", "Revise lo que esta buscando")



    def retranslateUi(self, WindowEditarContenido):
        _translate = QtCore.QCoreApplication.translate
        WindowEditarContenido.setWindowTitle(_translate("WindowEditarContenido", "Editar Contenido"))
        self.label.setText(_translate("WindowEditarContenido", "TÍTULO DE LA SOLUCIÓN:"))
        self.lineEdit.setPlaceholderText(_translate("WindowEditarContenido", "Escriba el título de la solución a ingresar (ej. cómo reinscribirse)"))
        self.lineEdit_3.setPlaceholderText(_translate("WindowEditarContenido", "Describa la solución"))
        self.label_2.setText(_translate("WindowEditarContenido", "ÁREA DE SERVICIO:"))
        self.label_3.setText(_translate("WindowEditarContenido", "SOLUCIÓN:"))
        self.btn_Nuevo.setText(_translate("WindowEditarContenido", "Actualizar"))
        self.btn_Eliminar.setText(_translate("WindowEditarContenido", "Cancelar"))
        self.lineEdit_2.setPlaceholderText(_translate("WindowEditarContenido", "Escriba el título de la solución a ingresar (ej. cómo reinscribirse)"))
        self.label_4.setText(_translate("WindowEditarContenido", "PALABRA CLAVE:"))
        self.lineEdit_4.setPlaceholderText(_translate("WindowEditarContenido", "Escriba el título de la solución a ingresar (ej. cómo reinscribirse)"))
        self.label_5.setText(_translate("WindowEditarContenido", "BUSCAR POR TÍTULO DE LA SOLUCIÓN:"))
        self.lineEdit_5.setPlaceholderText(_translate("WindowEditarContenido", "BUSCAR..."))
        self.btn_Nuevo_2.setText(_translate("WindowEditarContenido", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowEditarContenido = QtWidgets.QDialog()
    ui = Ui_WindowEditarContenido()
    ui.setupUi(WindowEditarContenido)
    WindowEditarContenido.show()
    sys.exit(app.exec_())
