# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditarEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editarEditor(object):
    def setupUi(self, editarEditor):
        editarEditor.setObjectName("editarEditor")
        editarEditor.resize(538, 469)
        editarEditor.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label = QtWidgets.QLabel(editarEditor)
        self.label.setGeometry(QtCore.QRect(30, 50, 141, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 471, 41))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 160, 471, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 230, 471, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 300, 191, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(editarEditor)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 141, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(editarEditor)
        self.label_3.setGeometry(QtCore.QRect(30, 210, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(editarEditor)
        self.label_4.setGeometry(QtCore.QRect(40, 280, 141, 16))
        self.label_4.setObjectName("label_4")
        self.btn_Nuevo = QtWidgets.QPushButton(editarEditor)
        self.btn_Nuevo.setGeometry(QtCore.QRect(30, 420, 115, 30))
        self.btn_Nuevo.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo.setFlat(False)
        self.btn_Nuevo.setObjectName("btn_Nuevo")
        self.btn_Nuevo_2 = QtWidgets.QPushButton(editarEditor)
        self.btn_Nuevo_2.setGeometry(QtCore.QRect(410, 420, 115, 30))
        self.btn_Nuevo_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo_2.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo_2.setFlat(False)
        self.btn_Nuevo_2.setObjectName("btn_Nuevo_2")
        self.btn_Nuevo_3 = QtWidgets.QPushButton(editarEditor)
        self.btn_Nuevo_3.setGeometry(QtCore.QRect(280, 420, 115, 30))
        self.btn_Nuevo_3.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo_3.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo_3.setFlat(False)
        self.btn_Nuevo_3.setObjectName("btn_Nuevo_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 10, 371, 41))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(editarEditor)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 61, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QtCore.QRect(450, 320, 16, 16))
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(editarEditor)
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setGeometry(QtCore.QRect(300, 300, 171, 41))
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(179, 179, 179);\n"
"    padding-top:1px;\n"
"    border-radius:20px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_6 = QtWidgets.QLabel(editarEditor)
        self.label_6.setGeometry(QtCore.QRect(300, 280, 141, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.btn_Nuevo.raise_()
        self.btn_Nuevo_2.raise_()
        self.btn_Nuevo_3.raise_()
        self.lineEdit_5.raise_()
        self.label_5.raise_()
        self.lineEdit_7.raise_()
        self.label_6.raise_()

        self.retranslateUi(editarEditor)
        self.btn_Nuevo_2.clicked.connect(editarEditor.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(editarEditor)

        self.btn_Nuevo.clicked.connect(self.buscar_por_correo_actualizar)
        self.btn_Nuevo_3.clicked.connect(self.modificar_rol)

    def buscar_por_correo_actualizar(self):
        self.var_1 = str
        self.var_2 = str
        id_user = self.lineEdit_5.text()
        id_user = str("'" + id_user + "'")
        from windows import Conexion
        self.datos = Conexion.DataBase()
        self.correo = self.datos.buscar_usuarios(id_user)
        if len(self.correo) != 0:
            self.Id = self.correo[0][0]
            self.lineEdit.setText(self.correo[0][1])
            self.lineEdit_2.setText(self.correo[0][2])
            self.lineEdit_3.setText(self.correo[0][3])
            self.lineEdit_4.setText(self.correo[0][4])
            self.lineEdit_6.setText(self.correo[0][5])
            self.lineEdit_7.setText(self.correo[0][6])
        else:
            import tkinter
            from tkinter import messagebox
            error = tkinter.messagebox.showerror("No exite", "No existen estos datos")

    def modificar_rol(self):
        if self.correo != '':
            nombre = self.lineEdit.text()
            apellido = self.lineEdit_2.text()
            correo_electronico = self.lineEdit_3.text()
            rol = self.lineEdit_4.text()
            password_1 = self.lineEdit_6.text()
            numero_empleado = self.lineEdit_7.text()
            from windows import Conexion
            self.datos = Conexion.DataBase()
            print("pasa")
            self.act = self.datos.actualizar_usuario(self.Id, nombre, apellido, correo_electronico, rol, password_1, numero_empleado)

            if self.act == 1:
                import tkinter
                from tkinter import messagebox
                hecho = tkinter.messagebox.showinfo("Actualzado", "Los datos fueron actualizados satisfactoriamente")
                print("xd")
            elif self.act == 0:
                print("error")
            else:
                import tkinter
                from tkinter import messagebox
                hecho = tkinter.messagebox.showinfo("Posiblemente hay un error", "Revise lo que esta buscando")


    def retranslateUi(self, editarEditor):
            _translate = QtCore.QCoreApplication.translate
            editarEditor.setWindowTitle(_translate("editarEditor", "Dialog"))
            self.label.setText(_translate("editarEditor", "NOMBRE:"))
            self.lineEdit.setPlaceholderText(_translate("editarEditor", "Nombre"))
            self.lineEdit_2.setPlaceholderText(_translate("editarEditor", "Apellido"))
            self.lineEdit_3.setPlaceholderText(_translate("editarEditor", "Correo electrónico"))
            self.lineEdit_4.setPlaceholderText(_translate("editarEditor", "Rol----- Editor = 1  ,   Estudiante = 0"))
            self.label_2.setText(_translate("editarEditor", "APELLIDO"))
            self.label_3.setText(_translate("editarEditor", "CORREO ELECTRÓNICO:"))
            self.label_4.setText(_translate("editarEditor", "ROL:"))
            self.btn_Nuevo.setText(_translate("editarEditor", "Buscar"))
            self.btn_Nuevo_2.setText(_translate("editarEditor", "Cancelar"))
            self.btn_Nuevo_3.setText(_translate("editarEditor", "Actualizar"))
            self.lineEdit_5.setPlaceholderText(_translate("editarEditor", "Buscar por correo"))
            self.label_5.setText(_translate("editarEditor", "Busqueda"))
            self.lineEdit_6.setPlaceholderText(_translate("editarEditor", "password"))
            self.lineEdit_7.setPlaceholderText(_translate("editarEditor", "numero_empleado"))
            self.label_6.setText(_translate("editarEditor", "Número Empleado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editarEditor = QtWidgets.QDialog()
    ui = Ui_editarEditor()
    ui.setupUi(editarEditor)
    editarEditor.show()
    sys.exit(app.exec_())
