# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaAdmin(object):
    def setupUi(self, VentanaAdmin):
        VentanaAdmin.setObjectName("VentanaAdmin")
        VentanaAdmin.resize(1028, 501)
        VentanaAdmin.setMinimumSize(QtCore.QSize(1000, 500))
        VentanaAdmin.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(VentanaAdmin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(212, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(0, 46, 109);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_chat = QtWidgets.QPushButton(self.frame_3)
        self.btn_chat.setGeometry(QtCore.QRect(20, 90, 171, 30))
        self.btn_chat.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_chat.setStyleSheet("QPushButton {\n"
"    font: 11.5pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:-90px;\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_chat.setFlat(False)
        self.btn_chat.setObjectName("btn_chat")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 101, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11.5pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(80, 31, 101, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 11pt \"Calibri Light\";\n"
"background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.btn_about = QtWidgets.QPushButton(self.frame_3)
        self.btn_about.setGeometry(QtCore.QRect(20, 210, 171, 30))
        self.btn_about.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_about.setStyleSheet("QPushButton {\n"
"    font: 11.5pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:-27px;\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_about.setFlat(False)
        self.btn_about.setObjectName("btn_about")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 51, 41))
        self.label_4.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../img/ico.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.btn_about_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_about_2.setGeometry(QtCore.QRect(20, 170, 171, 30))
        self.btn_about_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_about_2.setStyleSheet("QPushButton {\n"
"    font: 11.5pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:-2px;\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_about_2.setFlat(False)
        self.btn_about_2.setObjectName("btn_about_2")
        self.btn_about_7 = QtWidgets.QPushButton(self.frame_3)
        self.btn_about_7.setGeometry(QtCore.QRect(20, 130, 171, 30))
        self.btn_about_7.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_about_7.setStyleSheet("QPushButton {\n"
"    font: 11.5pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:0px;\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_about_7.setFlat(False)
        self.btn_about_7.setObjectName("btn_about_7")
        self.btn_cerrarSesion = QtWidgets.QPushButton(self.frame_3)
        self.btn_cerrarSesion.setGeometry(QtCore.QRect(30, 480, 171, 30))
        self.btn_cerrarSesion.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cerrarSesion.setStyleSheet("QPushButton {\n"
"    font: 9pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:-50px;\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_cerrarSesion.setFlat(False)
        self.btn_cerrarSesion.setObjectName("btn_cerrarSesion")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_pages.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.page_1)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(217, 217, 217);\n"
"    border-radius:26px;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_input_messages = QtWidgets.QFrame(self.frame)
        self.frame_input_messages.setGeometry(QtCore.QRect(10, 400, 721, 71))
        self.frame_input_messages.setStyleSheet("QFrame{\n"
"    \n"
"    \n"
"    \n"
"    padding-top:1px;\n"
"    border-radius:25px;\n"
"}")
        self.frame_input_messages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_messages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_messages.setObjectName("frame_input_messages")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_input_messages)
        self.lineEdit.setGeometry(QtCore.QRect(100, 9, 601, 51))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(167, 182, 203);\n"
"    padding-top:1px;\n"
"    border-radius:25px;\n"
"    \n"
"    border-color: rgb(0, 46, 109);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_input_messages)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.label_5.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../img/ico.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(217, 217, 217);\n"
"    border-radius:26px;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 4, 1, 1)
        self.btn_Nuevo_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Nuevo_4.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo_4.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo_4.setFlat(False)
        self.btn_Nuevo_4.setObjectName("btn_Nuevo_4")
        self.gridLayout_4.addWidget(self.btn_Nuevo_4, 0, 4, 1, 1)
        self.btn_Nuevo_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_Nuevo_3.setEnabled(False)
        self.btn_Nuevo_3.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo_3.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(210, 0, 0);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo_3.setFlat(False)
        self.btn_Nuevo_3.setObjectName("btn_Nuevo_3")
        self.gridLayout_4.addWidget(self.btn_Nuevo_3, 0, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 2, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.frame_7 = QtWidgets.QFrame(self.page_8)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 778, 498))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: rgb(217, 217, 217);\n"
"    border-radius:26px;\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 751, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.gridLayout_5.addLayout(self.verticalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 2, 3, 1, 1)
        self.btn_Nuevo_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_Nuevo_5.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Nuevo_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Nuevo_5.setStyleSheet("QPushButton {\n"
"    \n"
"    font: 14pt \"Calibri\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 46, 109);\n"
"    border: 0px solid;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(93, 129, 163);\n"
"}\n"
"\n"
"\n"
"    \n"
"    \n"
"    \n"
"    \n"
"")
        self.btn_Nuevo_5.setFlat(False)
        self.btn_Nuevo_5.setObjectName("btn_Nuevo_5")
        self.gridLayout_5.addWidget(self.btn_Nuevo_5, 0, 5, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.page_8)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 781, 501))
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color: rgb(217, 217, 217);\n"
"    border-radius:26px;\n"
"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_25 = QtWidgets.QLabel(self.frame_8)
        self.label_25.setGeometry(QtCore.QRect(370, 190, 141, 61))
        self.label_25.setStyleSheet("font: 16pt \"Calibri\";")
        self.label_25.setObjectName("label_25")
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        VentanaAdmin.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaAdmin)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(VentanaAdmin)
        self.btn_chat.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_1))
        self.btn_about_7.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        self.btn_about_2.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_8))
        self.btn_about.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page))
        self.btn_Nuevo_5.clicked.connect(self.agregarEditor)
        self.btn_cerrarSesion.clicked.connect(VentanaAdmin.close)
        self.btn_cerrarSesion.clicked.connect(self.cerrarSesion)

    def cerrarSesion(self):
        self.ventana = QtWidgets.QMainWindow()
        from ventanas.VentanaIngreso import Ui_VentanaIngreso
        self.ui = Ui_VentanaIngreso()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
    def agregarEditor(self):
        self.ventana = QtWidgets.QMainWindow()
        from ventanas.AgregarEditor import Ui_agregarEditor
        self.ui = Ui_agregarEditor()
        self.ui.setupUi(self.ventana)
        self.ventana.show()
    def retranslateUi(self, VentanaAdmin):
        _translate = QtCore.QCoreApplication.translate
        VentanaAdmin.setWindowTitle(_translate("VentanaAdmin", "MainWindow"))
        self.btn_chat.setText(_translate("VentanaAdmin", "Chat"))
        self.label_2.setText(_translate("VentanaAdmin", "Nombre_user"))
        self.label_3.setText(_translate("VentanaAdmin", "Administrador"))
        self.btn_about.setText(_translate("VentanaAdmin", "Sobre Foxy Bot"))
        self.btn_about_2.setText(_translate("VentanaAdmin", "Gestión de editores"))
        self.btn_about_7.setText(_translate("VentanaAdmin", "Gestion de servicios"))
        self.btn_cerrarSesion.setText(_translate("VentanaAdmin", "Cerrar Sesión"))
        self.label_15.setText(_translate("VentanaAdmin", "Titulo"))
        self.label_16.setText(_translate("VentanaAdmin", "Fecha de adición"))
        self.label_13.setText(_translate("VentanaAdmin", "Numero de soluciones"))
        self.label_14.setText(_translate("VentanaAdmin", "Agregado por "))
        self.btn_Nuevo_4.setText(_translate("VentanaAdmin", "+Nuevo"))
        self.btn_Nuevo_3.setText(_translate("VentanaAdmin", "Eliminar"))
        self.label_18.setText(_translate("VentanaAdmin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Gestión de servicios</span></p></body></html>"))
        self.label_19.setText(_translate("VentanaAdmin", "Estado"))
        self.label_20.setText(_translate("VentanaAdmin", "Nombre"))
        self.label_21.setText(_translate("VentanaAdmin", "Fecha de adición"))
        self.label_22.setText(_translate("VentanaAdmin", "Correo electronico"))
        self.label_23.setText(_translate("VentanaAdmin", "Núm. Empleado"))
        self.label_24.setText(_translate("VentanaAdmin", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Gestión de editores</span></p></body></html>"))
        self.btn_Nuevo_5.setText(_translate("VentanaAdmin", "+Nuevo"))
        self.label_25.setText(_translate("VentanaAdmin", "<html><head/><body><p><span style=\" font-size:18pt;\">FOXYBOT v0.1</span></p></body></html>"))
        self.btn_cerrarSesion.clicked.connect(self.cerrarSesion)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaAdmin = QtWidgets.QMainWindow()
    ui = Ui_VentanaAdmin()
    ui.setupUi(VentanaAdmin)
    VentanaAdmin.show()
    sys.exit(app.exec_())
